language: cpp
compiler:
  - g++
  - clang
  
branches:
  only:
    - master
    - development

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install liballegro5-dev
script: bash test.sh
